#!/bin/sh

echo "パスワードマネージャーへようこそ！"
echo "次の選択肢から入力してください(Add Password/Get Password/Exit)：
"
read userInput

if [ $userInput = "Add Password" ]; then
    echo "サービス名を入力してください："
    read serviceName
    echo $serviceName >> outputfile.txt
elif [ $userInput = "Get Password" ]; then
    echo "ユーザー名を入力してください："
elif [ $userInput = "Exit" ]; then
    echo "Thank you!"
else
    echo "入力が間違えています。Add Password/Get Password/Exit から入力してください。"
fi




#echo "パスワードを入力してください："
