#!/bin/sh

echo "パスワードマネージャーへようこそ！"

while true; do
    echo "次の選択肢から入力してください(Add Password/Get Password/Exit)：
"
    read userInput

    if [ "$userInput" = "Add Password" ]; then
        echo "サービス名を入力してください："
        read serviceName
        echo $serviceName >> outputfile.txt
    elif [ "$userInput" = "Get Password" ]; then
        echo "ユーザー名を入力してください："
        read userName
        echo $userName >> outputfile.txt
    elif [ "$userInput" = "Exit" ]; then
        echo "Thank you!"
        break
    else
        echo "入力が間違えています。Add Password/Get Password/Exit から入力してください。"
    fi
done

#echo "パスワードを入力してください："
#ファイル内でテキストを検索：grep "search text" file.txt
